### ISSUE TITLE
text_to_word_sequence提示错误

### ISSUE THREAD

**Issue by AlexYoung757** [renjunxiang/Competiton_CAIL#1]
text_to_word_sequence
    text = text.lower()
AttributeError: 'list' object has no attribute 'lower'

**Comment by renjunxiang** [comment]
I'm sorry for answering you at this moment bacause busy recently.
This code was only an idea for the competition, and there was several mistake in functions.
My full code haven't push to repo bacause organizers warned me if others' submission same as mine, both will be invalid.
You can use 'from keras.preprocessing.text import Tokenizer' to deal with it.

**Comment by celtics7** [comment]
the input of fit_on_texts() and texts_to_sequences() must be the list of string,
but the data_transform.py the input of these two function is the list of list,
result in AttributeError: 'list' object has no attribute 'lower'

**Comment by renjunxiang** [comment]
@celtics7 
Maybe your version is old. I have tried yet.
 
>>> from keras.preprocessing.text import Tokenizer
>>> texts=[['a','b'],['a','b']]
>>> tokenizer=Tokenizer()
>>> tokenizer.fit_on_texts(texts)
>>> tokenizer.texts_to_sequences(texts)
[[1, 2], [1, 2]]

**Comment by AlexYoung757** [comment]
大兄弟 可以做做DC平台达观的题目哦  这题可以用lda做预处理 然后再放入到nn里面

**Comment by renjunxiang** [comment]
@AlexYoung757 好的呀，有空我去试试哈~
