### ISSUE TITLE
model_CNN_attention_accusation.py错误

### ISSUE THREAD

**Issue by wangxupeng** [renjunxiang/Competiton_CAIL#3]
在跑model_CNN_attention_accusation.py 的时候 第一个epoch结束之后 再次循环的时候爆出
Traceback (most recent call last):
  File "model_CNN_TextCNN_accusation.py", line 71, in <module>
    model.fit(x=fact_train, y=labels_train, batch_size=512, epochs=1, verbose=1)
NameError: name 'model' is not defined

**Comment by renjunxiang** [comment]
你这里是在71行报错，和我位置不一样，你应该是做了什么修改，贴一下71行附近的代码。
这里的思路就是一个循环跑一个epoch，保存模型，然后计算accu和f1；再到下一个循环。如果你的可以成功保存并计算，那应该是没问题的。你这里是不是model被你删掉了或者你自己写了函数包装后mode是局部变量？ @wangxupeng

**Comment by wangxupeng** [comment]
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Model
from keras.layers import Dense, Embedding, Input, Dropout
from keras.layers import BatchNormalization, Concatenate
import pandas as pd
import time
from keras.models import load_model
import sys

sys.path.append(r"../")
from evaluate import predict2both, predict2half, predict2top, f1_avg
from textcnn import textcnn_one
import gc

print('start', time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()))
print('accusation')

num_words = 80000
maxlen = 400
filters = 256
print('num_words = 80000, maxlen = 400')

# fact数据集
train_fact = np.load('./data/train_fact_seq_pad.npy')
valid_fact = np.load('./data/valid_fact_seq_pad.npy')
fact_test = np.load('./data/test_fact_seq_pad.npy')
fact_train = np.vstack((train_fact, valid_fact))
del train_fact
del valid_fact
gc.collect()

# 标签数据集
train_label = np.load('./data/train_accusation_label.npy')
valid_label = np.load('./data/valid_accusation_label.npy')
labels_test = np.load('./data/test_accusation_label.npy')
labels_train = np.vstack((train_label, valid_label))
del train_label
del valid_label
gc.collect()

# set_accusation = np.load('./data_deal/set/set_accusation.npy')

data_input = Input(shape=[maxlen])
word_vec = Embedding(input_dim=num_words + 1,
                     input_length=maxlen,
                     output_dim=512,
                     mask_zero=False,
                     name='Embedding')(data_input)

x1 = textcnn_one(word_vec=word_vec, kernel_size=1, filters=filters)
x2 = textcnn_one(word_vec=word_vec, kernel_size=2, filters=filters)
x3 = textcnn_one(word_vec=word_vec, kernel_size=3, filters=filters)
x4 = textcnn_one(word_vec=word_vec, kernel_size=4, filters=filters)
x5 = textcnn_one(word_vec=word_vec, kernel_size=5, filters=filters)

x = Concatenate(axis=1)([x1, x2, x3, x4, x5])
x = BatchNormalization()(x)
x = Dense(1000, activation="relu")(x)
x = Dropout(0.2)(x)
x = Dense(labels_train.shape[1], activation="sigmoid")(x)
model = Model(inputs=data_input, outputs=x)
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

n_start = 1
n_end = 21
score_list1 = []
score_list2 = []
for i in range(n_start, n_end):
    model.fit(x=fact_train, y=labels_train, batch_size=512, epochs=1, verbose=1)

    model.save('./output/TextCNN_%d_epochs_%d.h5' % (filters, i))
    gc.collect()

    y = model.predict(fact_test[:])
    y1 = predict2top(y)
    y2 = predict2half(y)
    y3 = predict2both(y)
    del model
    del y
    gc.collect()

    print('%s accu:' % i)
    # 只取最高置信度的准确率
    s1 = [(labels_test[i] == y1[i]).min() for i in range(len(y1))]
    print(sum(s1) / len(s1))
    # 只取置信度大于0.5的准确率
    s2 = [(labels_test[i] == y2[i]).min() for i in range(len(y1))]
    print(sum(s2) / len(s2))
    # 结合前两个
    s3 = [(labels_test[i] == y3[i]).min() for i in range(len(y1))]
    print(sum(s3) / len(s3))

    print('%s f1:' % i)
    # 只取最高置信度的准确率
    s4 = f1_avg(y_pred=y1, y_true=labels_test)
    print("只取最高置信度的准确率:", s4)
    # 只取置信度大于0.5的准确率
    s5 = f1_avg(y_pred=y2, y_true=labels_test)
    print("只取置信度大于0.5的准确率:", s5)
    # 结合前两个
    s6 = f1_avg(y_pred=y3, y_true=labels_test)
    print("结合前两个:", s6)

    score_list1.append([i,
                        sum(s1) / len(s1),
                        sum(s2) / len(s2),
                        sum(s3) / len(s3)])
    score_list2.append([i, s4, s5, s6])

print(pd.DataFrame(score_list1))
print(pd.DataFrame(score_list2))
print('end', time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()))
print('#####################\n')
# nohup python model_CNN_accusation.py 2>&1 &

我就改了一下读取数据的路径  我用的小数据集然后其他的就没怎么改了 谢谢你

**Comment by wangxupeng** [comment]
我明白了 我手动启用了垃圾回收机制,应该是被回收了

**Comment by wangxupeng** [comment]
我已经成功复现你的代码了,其实你数据处理可以改一改,按照数据流的形式处理,然后保存的时候把int的type调小一点,我32G内存,GTX1080TI跑你的模型完全可以的.

**Comment by renjunxiang** [comment]
哈哈，好的。我没有处理内存的经验，你说的int type是numpy里面改吗？我当时是Tokenizer和pad_sequences这两步没办法一次性做，才分块去做的。最后生成的数据还好，data好像是5G，3个label加起来好像是10g。你是在这里把numpy.array的精度调低了吗？

**Comment by wangxupeng** [comment]
就是把dtype改一下

**Comment by renjunxiang** [comment]
我刚看了一下numpy.array，它里面写的：If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.应该不用改吧。

**Comment by wangxupeng** [comment]
默认值是int64  我存的要小一些

**Comment by renjunxiang** [comment]
哦哦，原来如此！难怪我当时直接保存keras的模型要500M，保存参数才100M，应该也是精度不同的原因。

**Comment by wangxupeng** [comment]
而且结巴分词的时候其实不用分块 这样很麻烦 你可以一条读进来分词,然后写入这一条 write的时候flush一下,不过我存的和你不一样 我第一步的时候分词结果存的txt

**Comment by renjunxiang** [comment]
我懂了，你是逐条处理的然后写入文件，所以一边写一边删就好了，类似读文件用readline的方式。我当时图方便，想快一些，直接内存里面做的，分块写进pkl。内存不够的时候你这个方法倒是挺好的，我还没用过数据流处理过数据，要学习一下。

**Comment by wangxupeng** [comment]
嗯,大数据集结巴分词,另外我自己还加了去停用词,全程跑完44分钟搞定

**Comment by DreamDQ** [comment]
您好，请问您这个attention模型是什么原理能稍微介绍下吗 不是很明白这个作用是什么 TT 谢谢啦

**Comment by renjunxiang** [comment]
你好，可以参考<https://github.com/philipperemy/keras-attention-mechanism>，大致思想是：1.计算每个时间步的均值；2.计算时间步之间的权重；3.将权重扩充至原始数据的shape，得到注意力权重；4.注意力权重乘以原始数据得到注意力加权后的信息 @huangdeqin
