### ISSUE TITLE
能提供一下 数据集下载地址吗 比如百度网盘链接

### ISSUE THREAD

**Issue by wind91725** [renjunxiang/Competiton_CAIL#4]
官网 现在不让注册了好像 我们现在需要这个数据集 去做些事情 能提供下 数据集吗 谢谢

**Comment by renjunxiang** [comment]
你好，已经上传网盘：https://pan.baidu.com/s/12KS55iDynnEgmOM8FEaJtQ

**Comment by renjunxiang** [comment]
你好，已经上传网盘：https://pan.baidu.com/s/12KS55iDynnEgmOM8FEaJtQ
