### ISSUE TITLE
请问train.py是没有上传吗？

### ISSUE THREAD

**Issue by binaryOmaire** [renjunxiang/Competiton_CAIL#7]

**Comment by renjunxiang** [comment]
model_xxx_xxx.py就是训练的脚本，没有单独封装网络哈，直接把网络写进训练脚本了

**Comment by binaryOmaire** [comment]
你的预测是单个句子。我想把训练好的模型取出来，在测试集上求f1，怎么做呢？

**Comment by renjunxiang** [comment]
预测的是句子组成的列表，参见predictor/predictor.py。
模型的输入是经过tokenizer编码后的数字序列：假设训练的时候。句子长度=maxlen，罪名数=num；预测的时候，输入的是[batchsze,]的文本列表，经过分词、tokenizer编码后变成shape=[batchsze,maxlen]的二维编码数组，输出就是shape=[batchsze,num]的概率矩阵，再和标签通过sklearn.metrics.scorer.f1_score计算就可以了。

**Comment by binaryOmaire** [comment]
cnn+attention，attention放在模型哪一个位置有什么考量吗？

**Comment by renjunxiang** [comment]
运行model_CNN_attention_accusation.py即可，网络在脚本里面。
``` python
data_input = Input(shape=[maxlen])
word_vec = Embedding(input_dim=num_words + 1,
                     input_length=maxlen,
                     output_dim=512,
                     mask_zero=0,
                     name='Embedding')(data_input)
x = word_vec
x = Conv1D(filters=512, kernel_size=[3], strides=1, padding='same', activation='relu')(x)
x = attention(input=x, depth=512)
x = GlobalMaxPool1D()(x)
x = BatchNormalization()(x)
x = Dense(1000, activation="relu")(x)
x = Dropout(0.2)(x)
x = Dense(labels_train.shape[1], activation="sigmoid")(x)
model = Model(inputs=data_input, outputs=x)
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
```

**Comment by binaryOmaire** [comment]
请问练习赛当时是提供train、valid、test数据集，然后主办方再用别的数据测一下？
请问你的练习赛最后成绩是多少，有练习赛排行榜吗？我现在用练习赛数据做，发现离官网的第一阶段排行榜差好多。samll根本达不到big数据集那么高的f1。。。。。。

**Comment by renjunxiang** [comment]
是的。练习赛我记得大概是5月底结束的，都是用small训练的模型，我有贴图，后续的练习赛榜单是很多人用big训练的模型去刷的。
